/*

This is a JavaScript file you can edit to add custom markers to the map.
uNmINeD does not overwrite this file during map generation.

Steps:

    1. Edit this file using Notepad or a code editor (do not use document editors like Microsoft Word)
    2. Change the line "isEnabled: false," to "isEnabled: true," to display the markers
    3. Change or remove the example markers
    4. Add your own markers

Marker format:

    {
        x: X coordinate of the marker (in Minecraft block units),
        z: Z coordinate of the marker (in Minecraft block units),
        image: marker image URL to display (in quotes),
        imageScale: scale of the image (e.g. 1 = display full size, 0.5 = display half size),
        imageAnchor: [0.5, 1] means the tip of the pin is at the center-bottom of the image (see OpenLayers documentation for more info),
        text: marker text do display (in quotes),
        textColor: text color in HTML/CSS format (in quotes),
        offsetX: horizontal pixel offset of the text,
        offsetY: vertical pixel offset of the text,
        font: text font in HTML/CSS format (in quotes),
    },

Things to keep in mind:

* There are opening and closing brackets for each marker "{" and "}"
* Property names are case sensitive (i.e. "textColor" is okay, "TextColor" is not)
* There is a comma (",") at the end of each line except the opening brackets ("{")

You can use https://mapmarker.io/editor to generate custom pin images.
Use the imageScale property if the pin image is too large.

*/

UnminedCustomMarkers = {

    isEnabled: true,

    markers: [

        // Example 1: Simple marker
/*        {
            x: -200,
            z: -200,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.2,
        },*/

        // Example 2: Marker with text
        {
            x: 0,
            z: 0,
            image: "WorldCenter.svg",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "World Center 0/0",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },

        // Example 3: Text only
/*        {
            x: 200,
            z: 200,
            text: "Text only", 
            textColor: "yellow", 
            offsetX: 0,
            offsetY: 0, 
            font: "bold 50px Calibri,sans serif",
        },
*/
        // add your markers here
        {
            x: 3064,
            z: 4,
            image: "Spawn.svg",
            imageAnchor: [0.5, 1],
            imageScale: 0.4,
            text: "Spawn",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2, 
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                {
            x: 1513,
            z: -384,
            image: "LlamaFace.webp",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Sam's Town",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2, 
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 1817,
            z: -650,
            image: "PillagerFace.webp",
            imageAnchor: [0.5, 1],
            imageScale: 0.7,
            text: "Raid | Iron Farm",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 2953,
            z: -665,
            image: "PillagerFace.webp",
            imageAnchor: [0.5, 1],
            imageScale: 0.6,
            text: "Pillager Outpost",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 471,
            z: -1046,
            image: "PillagerFace.webp",
            imageAnchor: [0.5, 1],
            imageScale: 0.6,
            text: "Pillager Outpost",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 4135,
            z: 1976,
            image: "PillagerFace.webp",
            imageAnchor: [0.5, 1],
            imageScale: 0.6,
            text: "Pillager Outpost",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 4407,
            z:-1798,
            image: "PillagerFace.webp",
            imageAnchor: [0.5, 1],
            imageScale: 0.6,
            text: "Pillager Outpost",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 4313,
            z: 298,
            image: "PillagerFace.webp",
            imageAnchor: [0.5, 1],
            imageScale: 0.6,
            text: "Pillager Outpost",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 5737,
            z: 4170,
            image: "PillagerFace.webp",
            imageAnchor: [0.5, 1],
            imageScale: 0.6,
            text: "Pillager Outpost",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },        {
            x: 5257,
            z: 1834,
            image: "PillagerFace.webp",
            imageAnchor: [0.5, 1],
            imageScale: 0.6,
            text: "Pillager Outpost",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 5336,
            z: 3175,
            image: "PillagerFace.webp",
            imageAnchor: [0.5, 1],
            imageScale: 0.6,
            text: "Pillager Outpost",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                {
            x: 1502,
            z: -443,
            image: "WitherSkeletonFace.webp",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Wither Skeleton Farm",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                        {
            x: 3430,
            z: -3727,
            image: "PandaFace.webp",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Bamboo Jungle Portal",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                {
            x: 2561,
            z: -329,
            image: "IronGolemFace.webp",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Clament Siren's Iron Farm",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 2282,
            z: -557,
            image: "PlayerBase.svg",
            imageAnchor: [0.5, 1],
            imageScale: 0.4,
            text: "Clament Siren's Base",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                {
            x: 2784,
            z: -221,
            image: "PlayerBase.svg",
            imageAnchor: [0.5, 1],
            imageScale: 0.4,
            text: "Orchah's Base",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                {
            x: 2784,
            z: -273,
            image: "PlayerBase.svg",
            imageAnchor: [0.5, 1],
            imageScale: 0.4,
            text: "Stwawbeby's Base",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 1750,
            z: -777,
            image: "SlimeFace.webp",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Slime Farm",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 1740,
            z: -808,
            image: "EnderdragonFace.webp",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "End Portal Base",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },        
        {
            x: 1376,
            z: 127,
            image: "EnderdragonFace.webp",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "2nd End Portal Stronghold",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                {
            x: 2296,
            z: 136,
            image: "PlayerBase.svg",
            imageAnchor: [0.5, 1],
            imageScale: 0.4,
            text: "HipHopScotch's Base",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                {
            x: 1847,
            z: -947,
            image: "PlayerBase.svg",
            imageAnchor: [0.5, 1],
            imageScale: 0.4,
            text: "Gavin's Base",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                {
            x: 1824,
            z: -925,
            image: "PlayerBase.svg",
            imageAnchor: [0.5, 1],
            imageScale: 0.4,
            text: "Gabi's House",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                {
            x: 1697,
            z: -991,
            image: "Pearlescent_Froglight.webp",
            imageAnchor: [0.5, 1],
            imageScale: 0.1,
            text: "Frog Light Farm",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                {
            x: 4091,
            z: -2359,
            image: "Mega_Spruce_Tree.webp",
            imageAnchor: [0.5, 1],
            imageScale: 0.3,
            text: "Mega Taiga - Giant Spruce Forest",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                {
            x: 1354,
            z: -1960,
            image: "GuardianFace.webp",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Guardian/Fish/Squid Farm",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2, 
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                {
            x: 1400,
            z: -1933,
            image: "WanderingTraderFace.webp",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Fisherman Trading Hall",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                {
            x: 3227,
            z: -307,
            image: "WanderingTraderFace.webp",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Spawn Village Trading Hall & Farms",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2, 
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                {
            x: 3300,
            z: -107,
            image: "SnowGolemFace.webp",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Powdered Snow Farm",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                {
            x: 3237,
            z: -125,
            image: "StrayFace.webp",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Skeleton / Stray Farm",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                {
            x: 3591,
            z: 1400,
            image: "WanderingTraderFace.webp",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Underwater Trading Hall",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                        {
            x: 3460,
            z: 1420,
            image: "PlayerBase.svg",
            imageAnchor: [0.5, 1],
            imageScale: 0.4,
            text: "Schwvevils Base",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                                {
            x: 3112,
            z: -124,
            image: "IanBase.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.02 ,
            text: "Ian's Hobbit Hole",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                        {
            x: 2900,
            z: -6300,
            image: "Mangrove_Roots.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.2,
            text: "Large Mangrove Swamp",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                                {
            x: 7650,
            z: 709,
            image: "MooshroomFace.webp",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Mushroom Island",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                                {
            x: -3610,
            z: 2640,
            image: "MooshroomFace.webp",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Mushroom Island",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                                {
            x: 3820,
            z: 4670,
            image: "MooshroomFace.webp",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Mushroom Island",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                                {
            x: 1774,
            z: -618,
            image: "CreeperFace.webp",
            imageAnchor: [0.5, 1],
            imageScale: .5,
            text: "DonJuan's Creeper Farm",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                                {
            x: 1077,
            z: -585,
            image: "CreeperFace.webp",
            imageAnchor: [0.5, 1],
            imageScale: .5,
            text: "Clament Siren's Creeper Farm",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                                {
            x: -3720,
            z: -250,
            image: "PlayerBase.svg",
            imageAnchor: [0.5, 1],
            imageScale: 0.4,
            text: "QuarryMan's Base",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                                {
            x: 2183,
            z: 110,
            image: "WanderingTraderFace.webp",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "HipHopScotch's Trading Hall",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
/*                                        {
            x: 1912,
            z: 648,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.2,
            text: "No Idea? What is this?",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },*/
                                        {
            x: 3525,
            z: -5658,
            image: "WitherFace.webp",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Wither Battle Base",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                                        {
            x: 3635,
            z: -1515,
            image: "WitchFace.webp",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Witch Hut",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                                        {
            x: 3828,
            z: 4853,
            image: "WitchFace.webp",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Witch Hut",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                                       {
            x: 2100,
            z: -3291,
            image: "WitchFace.webp",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Witch Hut",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                                                {
            x: -144,
            z: -1312,
            image: "Cherry_Leaves.webp",
            imageAnchor: [0.5, 1],
            imageScale: 0.1,
            text: "Small Cherry Blossom Biome",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                                                {
            x: 3609,
            z: -495,
            image: "PlayerBase.svg",
            imageAnchor: [0.5, 1],
            imageScale: 0.4,
            text: "QuinRenee's Base",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                                                {
            x: 9862,
            z: 693,
            image: "Geode.webp",
            imageAnchor: [0.5, 1],
            imageScale: 0.05,
            text: "Geode Farm",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                                                {
            x: 1969,
            z: -792,
            image: "ZombifiedPiglinFace.webp",
            imageAnchor: [0.5, 1],
            imageScale: 0.3,
            text: "Mr Wink's Gold Farm",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                                                        {
            x: -1328,
            z: 1290,
            image: "santa-claus-icon.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Christmas Village",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                                                        {
            x: 350,
            z: -4410,
            image: "Woodland_Mansion.webp",
            imageAnchor: [0.5, 1],
            imageScale: 0.08,
            text: "Woodland Mansion",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                                                        {
            x: 2792,
            z: 1735,
            image: "Ocean_Monument.webp",
            imageAnchor: [0.5, 1],
            imageScale: 0.1,
            text: "Ocean Monument",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                                                        {
            x: 2711,
            z: 2215,
            image: "Ocean_Monument.webp",
            imageAnchor: [0.5, 1],
            imageScale: 0.1,
            text: "Ocean Monument",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                                                        {
            x: 3880,
            z: 4408,
            image: "Ocean_Monument.webp",
            imageAnchor: [0.5, 1],
            imageScale: 0.1,
            text: "Ocean Monument",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                                                        {
            x: 3639,
            z: 3831,
            image: "Ocean_Monument.webp",
            imageAnchor: [0.5, 1],
            imageScale: 0.1,
            text: "Ocean Monument",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,  
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                                                                {
            x: 3580,
            z: -780,
            image: "grimmy_base_icon_tiny.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Grimmy's Swamp",
            textColor: "magenta",
            textStrokeColor: "black",
            textStrokeWidth: 2, 
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        // do not delete the following two closing brackets
    ]
}
